"""rename interval start and end columns

Revision ID: 09aee5ff7560
Revises: 37053c56d236
Create Date: 2022-01-22 13:26:31.113875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09aee5ff7560'
down_revision = '37053c56d236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_intervals_end_datetime', table_name='intervals')
    op.drop_index('ix_intervals_start_datetime', table_name='intervals')
    op.alter_column('intervals', 'start_datetime', new_column_name='start')
    op.alter_column('intervals', 'end_datetime', new_column_name='end')
    op.create_index(op.f('ix_intervals_end'), 'intervals', ['end'], unique=False)
    op.create_index(op.f('ix_intervals_start'), 'intervals', ['start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intervals_start'), table_name='intervals')
    op.drop_index(op.f('ix_intervals_end'), table_name='intervals')
    op.alter_column('intervals', 'start', new_column_name='start_datetime')
    op.alter_column('intervals', 'end', new_column_name='end_datetime')
    op.create_index('ix_intervals_start_datetime', 'intervals', ['start_datetime'], unique=False)
    op.create_index('ix_intervals_end_datetime', 'intervals', ['end_datetime'], unique=False)
    # ### end Alembic commands ###
