"""changed entry primary keys

Revision ID: 2224390dd0b5
Revises: f83cd1c2050a
Create Date: 2022-01-14 16:29:39.375878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2224390dd0b5'
down_revision = 'f83cd1c2050a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entries_id', table_name='entries')
    op.drop_column('entries', 'id')
    op.drop_column('entries', 'dedication')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('dedication', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('entries', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('entries_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.create_index('ix_entries_id', 'entries', ['id'], unique=False)
    # ### end Alembic commands ###
