"""add time to entries

Revision ID: 37053c56d236
Revises: 2224390dd0b5
Create Date: 2022-01-22 12:19:49.803017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm


# revision identifiers, used by Alembic.
revision = "37053c56d236"
down_revision = "2224390dd0b5"
branch_labels = None
depends_on = None

Base = orm.declarative_base()


class Activity(Base):
    __tablename__ = "activities"

    id = sa.Column(sa.Integer, primary_key=True, index=True, autoincrement=True)
    entries = orm.relationship("Entry", back_populates="activity", cascade="all")


class Interval(Base):
    __tablename__ = "intervals"

    id = sa.Column(sa.Integer, primary_key=True, index=True, autoincrement=True)
    start_datetime = sa.Column(sa.DateTime(timezone=True), index=True)
    end_datetime = sa.Column(sa.DateTime(timezone=True), index=True)

    entries = orm.relationship("Entry", back_populates="interval", cascade="all")


class Entry(Base):
    __tablename__ = "entries"

    interval_id = sa.Column(sa.Integer, sa.ForeignKey("intervals.id"), primary_key=True)
    activity_id = sa.Column(
        sa.Integer, sa.ForeignKey("activities.id"), primary_key=True
    )
    time = sa.Column(sa.Interval)

    interval = orm.relationship(Interval, back_populates="entries")
    activity = orm.relationship(Activity, back_populates="entries")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entries", sa.Column("time", sa.Interval(), nullable=True))
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    result = session.execute(sa.select(Entry)).scalars()
    for entry in result:
        entry.time = entry.interval.end_datetime - entry.interval.start_datetime
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entries", "time")
    # ### end Alembic commands ###
