"""activity name is uique

Revision ID: 4b3ebe8c304d
Revises: a840f20b3cf9
Create Date: 2022-01-30 05:17:08.197673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3ebe8c304d'
down_revision = 'a840f20b3cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('activities_name_unique', 'activities', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activities_name_unique', 'activities', type_='unique')
    # ### end Alembic commands ###
