"""added is_suspended column to activities

Revision ID: 7cbfd0db0ac6
Revises: 09aee5ff7560
Create Date: 2022-01-22 14:48:03.281532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbfd0db0ac6'
down_revision = '09aee5ff7560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'is_suspended')
    # ### end Alembic commands ###
