"""added is_suspended column to activities

Revision ID: a840f20b3cf9
Revises: 09aee5ff7560
Create Date: 2022-01-22 15:11:25.243356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a840f20b3cf9"
down_revision = "09aee5ff7560"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activities", sa.Column("is_suspended", sa.Boolean(), nullable=True))
    op.execute("UPDATE activities SET is_suspended = false")
    op.alter_column("activities", "is_suspended", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "is_suspended")
    # ### end Alembic commands ###
