"""change association primary keys

Revision ID: c585f1f67f16
Revises: 
Create Date: 2022-01-14 15:25:52.813795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c585f1f67f16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('association', 'child_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('association', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('association', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('association_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.alter_column('association', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('association', 'child_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
